/**
 * Canonical country list — see 05_GAME_ENGINE_SPECIFICATION.md.
 * 197 sovereign entities (kept from the original COTE list per the ratified decision).
 * Each entry carries its numeric ISO id (matches the globe geometry), display name,
 * continent, and curated aliases + historical names.
 */

export type ContinentKey =
  | 'north_america'
  | 'south_america'
  | 'europe'
  | 'asia'
  | 'africa'
  | 'oceania'

export interface Country {
  id: string
  name: string
  continent: ContinentKey
  aliases: string[]
}

export const CONTINENTS: { key: ContinentKey; label: string }[] = [
  { key: 'north_america', label: 'N. America' },
  { key: 'south_america', label: 'S. America' },
  { key: 'europe', label: 'Europe' },
  { key: 'asia', label: 'Asia' },
  { key: 'africa', label: 'Africa' },
  { key: 'oceania', label: 'Oceania' },
]

const AF = 'africa'
const AS = 'asia'
const EU = 'europe'
const NA = 'north_america'
const SA = 'south_america'
const OC = 'oceania'

export const ALL_COUNTRIES: Country[] = [
  { id: '4', name: 'Afghanistan', continent: AS, aliases: [] },
  { id: '8', name: 'Albania', continent: EU, aliases: [] },
  { id: '12', name: 'Algeria', continent: AF, aliases: [] },
  { id: '20', name: 'Andorra', continent: EU, aliases: [] },
  { id: '24', name: 'Angola', continent: AF, aliases: [] },
  { id: '28', name: 'Antigua and Barbuda', continent: NA, aliases: ['antigua', 'barbuda', 'antigua barbuda'] },
  { id: '32', name: 'Argentina', continent: SA, aliases: [] },
  { id: '51', name: 'Armenia', continent: EU, aliases: [] },
  { id: '36', name: 'Australia', continent: OC, aliases: ['aus', 'aussie'] },
  { id: '40', name: 'Austria', continent: EU, aliases: [] },
  { id: '31', name: 'Azerbaijan', continent: EU, aliases: [] },
  { id: '44', name: 'Bahamas', continent: NA, aliases: ['the bahamas'] },
  { id: '48', name: 'Bahrain', continent: AS, aliases: [] },
  { id: '50', name: 'Bangladesh', continent: AS, aliases: [] },
  { id: '52', name: 'Barbados', continent: NA, aliases: [] },
  { id: '112', name: 'Belarus', continent: EU, aliases: ['byelorussia', 'belorussia'] },
  { id: '56', name: 'Belgium', continent: EU, aliases: [] },
  { id: '84', name: 'Belize', continent: NA, aliases: [] },
  { id: '204', name: 'Benin', continent: AF, aliases: [] },
  { id: '64', name: 'Bhutan', continent: AS, aliases: [] },
  { id: '68', name: 'Bolivia', continent: SA, aliases: [] },
  { id: '70', name: 'Bosnia and Herzegovina', continent: EU, aliases: ['bosnia', 'bosnia herzegovina', 'bih'] },
  { id: '72', name: 'Botswana', continent: AF, aliases: [] },
  { id: '76', name: 'Brazil', continent: SA, aliases: ['brasil'] },
  { id: '96', name: 'Brunei', continent: AS, aliases: ['brunei darussalam'] },
  { id: '100', name: 'Bulgaria', continent: EU, aliases: [] },
  { id: '854', name: 'Burkina Faso', continent: AF, aliases: ['burkina'] },
  { id: '108', name: 'Burundi', continent: AF, aliases: [] },
  { id: '116', name: 'Cambodia', continent: AS, aliases: ['kampuchea'] },
  { id: '120', name: 'Cameroon', continent: AF, aliases: [] },
  { id: '124', name: 'Canada', continent: NA, aliases: [] },
  { id: '132', name: 'Cape Verde', continent: AF, aliases: ['cabo verde'] },
  { id: '140', name: 'Central African Republic', continent: AF, aliases: ['car', 'central africa'] },
  { id: '148', name: 'Chad', continent: AF, aliases: [] },
  { id: '152', name: 'Chile', continent: SA, aliases: [] },
  { id: '156', name: 'China', continent: AS, aliases: ['prc', 'peoples republic of china', 'zhongguo'] },
  { id: '170', name: 'Colombia', continent: SA, aliases: [] },
  { id: '174', name: 'Comoros', continent: AF, aliases: ['the comoros', 'comoro islands'] },
  { id: '178', name: 'Republic of the Congo', continent: AF, aliases: ['congo', 'congo republic', 'congo brazzaville', 'republic of congo'] },
  { id: '180', name: 'DR Congo', continent: AF, aliases: ['drc', 'democratic republic of the congo', 'democratic republic of congo', 'congo kinshasa', 'zaire'] },
  { id: '188', name: 'Costa Rica', continent: NA, aliases: [] },
  { id: '191', name: 'Croatia', continent: EU, aliases: ['hrvatska'] },
  { id: '192', name: 'Cuba', continent: NA, aliases: [] },
  { id: '196', name: 'Cyprus', continent: EU, aliases: [] },
  { id: '203', name: 'Czech Republic', continent: EU, aliases: ['czechia', 'czech'] },
  { id: '208', name: 'Denmark', continent: EU, aliases: [] },
  { id: '262', name: 'Djibouti', continent: AF, aliases: [] },
  { id: '212', name: 'Dominica', continent: NA, aliases: [] },
  { id: '214', name: 'Dominican Republic', continent: NA, aliases: ['dom rep'] },
  { id: '218', name: 'Ecuador', continent: SA, aliases: [] },
  { id: '818', name: 'Egypt', continent: AF, aliases: [] },
  { id: '222', name: 'El Salvador', continent: NA, aliases: ['salvador'] },
  { id: '226', name: 'Equatorial Guinea', continent: AF, aliases: [] },
  { id: '232', name: 'Eritrea', continent: AF, aliases: [] },
  { id: '233', name: 'Estonia', continent: EU, aliases: [] },
  { id: '748', name: 'Eswatini', continent: AF, aliases: ['swaziland'] },
  { id: '231', name: 'Ethiopia', continent: AF, aliases: ['abyssinia'] },
  { id: '242', name: 'Fiji', continent: OC, aliases: [] },
  { id: '246', name: 'Finland', continent: EU, aliases: ['suomi'] },
  { id: '250', name: 'France', continent: EU, aliases: [] },
  { id: '266', name: 'Gabon', continent: AF, aliases: [] },
  { id: '270', name: 'Gambia', continent: AF, aliases: ['the gambia'] },
  { id: '268', name: 'Georgia', continent: EU, aliases: [] },
  { id: '276', name: 'Germany', continent: EU, aliases: ['deutschland'] },
  { id: '288', name: 'Ghana', continent: AF, aliases: [] },
  { id: '300', name: 'Greece', continent: EU, aliases: ['hellas'] },
  { id: '308', name: 'Grenada', continent: NA, aliases: [] },
  { id: '320', name: 'Guatemala', continent: NA, aliases: [] },
  { id: '324', name: 'Guinea', continent: AF, aliases: [] },
  { id: '624', name: 'Guinea-Bissau', continent: AF, aliases: ['guinea bissau'] },
  { id: '328', name: 'Guyana', continent: SA, aliases: [] },
  { id: '332', name: 'Haiti', continent: NA, aliases: [] },
  { id: '340', name: 'Honduras', continent: NA, aliases: [] },
  { id: '348', name: 'Hungary', continent: EU, aliases: [] },
  { id: '352', name: 'Iceland', continent: EU, aliases: [] },
  { id: '356', name: 'India', continent: AS, aliases: ['bharat', 'hindustan'] },
  { id: '360', name: 'Indonesia', continent: AS, aliases: [] },
  { id: '364', name: 'Iran', continent: AS, aliases: ['persia'] },
  { id: '368', name: 'Iraq', continent: AS, aliases: [] },
  { id: '372', name: 'Ireland', continent: EU, aliases: ['eire', 'republic of ireland'] },
  { id: '376', name: 'Israel', continent: AS, aliases: [] },
  { id: '380', name: 'Italy', continent: EU, aliases: ['italia'] },
  { id: '384', name: 'Ivory Coast', continent: AF, aliases: ['cote divoire', 'cote d ivoire', "cote d'ivoire"] },
  { id: '388', name: 'Jamaica', continent: NA, aliases: [] },
  { id: '392', name: 'Japan', continent: AS, aliases: ['nippon', 'nihon'] },
  { id: '400', name: 'Jordan', continent: AS, aliases: [] },
  { id: '398', name: 'Kazakhstan', continent: AS, aliases: [] },
  { id: '404', name: 'Kenya', continent: AF, aliases: [] },
  { id: '296', name: 'Kiribati', continent: OC, aliases: [] },
  { id: '383', name: 'Kosovo', continent: EU, aliases: [] },
  { id: '414', name: 'Kuwait', continent: AS, aliases: [] },
  { id: '417', name: 'Kyrgyzstan', continent: AS, aliases: ['kyrgyz republic', 'kirghizia'] },
  { id: '418', name: 'Laos', continent: AS, aliases: ['lao', 'lao pdr'] },
  { id: '428', name: 'Latvia', continent: EU, aliases: [] },
  { id: '422', name: 'Lebanon', continent: AS, aliases: [] },
  { id: '426', name: 'Lesotho', continent: AF, aliases: [] },
  { id: '430', name: 'Liberia', continent: AF, aliases: [] },
  { id: '434', name: 'Libya', continent: AF, aliases: [] },
  { id: '438', name: 'Liechtenstein', continent: EU, aliases: [] },
  { id: '440', name: 'Lithuania', continent: EU, aliases: [] },
  { id: '442', name: 'Luxembourg', continent: EU, aliases: [] },
  { id: '450', name: 'Madagascar', continent: AF, aliases: [] },
  { id: '454', name: 'Malawi', continent: AF, aliases: ['nyasaland'] },
  { id: '458', name: 'Malaysia', continent: AS, aliases: [] },
  { id: '462', name: 'Maldives', continent: AS, aliases: [] },
  { id: '466', name: 'Mali', continent: AF, aliases: [] },
  { id: '470', name: 'Malta', continent: EU, aliases: [] },
  { id: '584', name: 'Marshall Islands', continent: OC, aliases: ['marshall'] },
  { id: '478', name: 'Mauritania', continent: AF, aliases: [] },
  { id: '480', name: 'Mauritius', continent: AF, aliases: [] },
  { id: '484', name: 'Mexico', continent: NA, aliases: [] },
  { id: '583', name: 'Micronesia', continent: OC, aliases: ['federated states of micronesia', 'fsm'] },
  { id: '498', name: 'Moldova', continent: EU, aliases: ['republic of moldova'] },
  { id: '492', name: 'Monaco', continent: EU, aliases: [] },
  { id: '496', name: 'Mongolia', continent: AS, aliases: [] },
  { id: '499', name: 'Montenegro', continent: EU, aliases: [] },
  { id: '504', name: 'Morocco', continent: AF, aliases: [] },
  { id: '508', name: 'Mozambique', continent: AF, aliases: [] },
  { id: '104', name: 'Myanmar', continent: AS, aliases: ['burma'] },
  { id: '516', name: 'Namibia', continent: AF, aliases: [] },
  { id: '520', name: 'Nauru', continent: OC, aliases: [] },
  { id: '524', name: 'Nepal', continent: AS, aliases: [] },
  { id: '528', name: 'Netherlands', continent: EU, aliases: ['holland', 'nederland'] },
  { id: '554', name: 'New Zealand', continent: OC, aliases: ['nz', 'aotearoa'] },
  { id: '558', name: 'Nicaragua', continent: NA, aliases: [] },
  { id: '562', name: 'Niger', continent: AF, aliases: [] },
  { id: '566', name: 'Nigeria', continent: AF, aliases: [] },
  { id: '408', name: 'North Korea', continent: AS, aliases: ['dprk', 'democratic peoples republic of korea'] },
  { id: '807', name: 'North Macedonia', continent: EU, aliases: ['macedonia', 'fyrom', 'former yugoslav republic of macedonia'] },
  { id: '578', name: 'Norway', continent: EU, aliases: ['norge'] },
  { id: '512', name: 'Oman', continent: AS, aliases: [] },
  { id: '586', name: 'Pakistan', continent: AS, aliases: [] },
  { id: '585', name: 'Palau', continent: OC, aliases: [] },
  { id: '275', name: 'Palestine', continent: AS, aliases: ['palestinian territories', 'west bank'] },
  { id: '591', name: 'Panama', continent: NA, aliases: [] },
  { id: '598', name: 'Papua New Guinea', continent: OC, aliases: ['png', 'papua'] },
  { id: '600', name: 'Paraguay', continent: SA, aliases: [] },
  { id: '604', name: 'Peru', continent: SA, aliases: [] },
  { id: '608', name: 'Philippines', continent: AS, aliases: ['pilipinas'] },
  { id: '616', name: 'Poland', continent: EU, aliases: ['polska'] },
  { id: '620', name: 'Portugal', continent: EU, aliases: [] },
  { id: '634', name: 'Qatar', continent: AS, aliases: [] },
  { id: '642', name: 'Romania', continent: EU, aliases: ['rumania'] },
  { id: '643', name: 'Russia', continent: EU, aliases: ['russian federation'] },
  { id: '646', name: 'Rwanda', continent: AF, aliases: [] },
  { id: '659', name: 'Saint Kitts and Nevis', continent: NA, aliases: ['st kitts', 'st kitts and nevis', 'saint kitts'] },
  { id: '662', name: 'Saint Lucia', continent: NA, aliases: ['st lucia'] },
  { id: '670', name: 'Saint Vincent and the Grenadines', continent: NA, aliases: ['st vincent', 'saint vincent', 'st vincent and the grenadines'] },
  { id: '882', name: 'Samoa', continent: OC, aliases: ['western samoa'] },
  { id: '674', name: 'San Marino', continent: EU, aliases: [] },
  { id: '678', name: 'Sao Tome and Principe', continent: AF, aliases: ['sao tome'] },
  { id: '682', name: 'Saudi Arabia', continent: AS, aliases: ['ksa'] },
  { id: '686', name: 'Senegal', continent: AF, aliases: [] },
  { id: '688', name: 'Serbia', continent: EU, aliases: [] },
  { id: '690', name: 'Seychelles', continent: AF, aliases: [] },
  { id: '694', name: 'Sierra Leone', continent: AF, aliases: [] },
  { id: '702', name: 'Singapore', continent: AS, aliases: [] },
  { id: '703', name: 'Slovakia', continent: EU, aliases: ['slovak republic'] },
  { id: '705', name: 'Slovenia', continent: EU, aliases: [] },
  { id: '90', name: 'Solomon Islands', continent: OC, aliases: ['solomons'] },
  { id: '706', name: 'Somalia', continent: AF, aliases: [] },
  { id: '710', name: 'South Africa', continent: AF, aliases: ['rsa'] },
  { id: '410', name: 'South Korea', continent: AS, aliases: ['korea', 'republic of korea', 'rok'] },
  { id: '728', name: 'South Sudan', continent: AF, aliases: [] },
  { id: '724', name: 'Spain', continent: EU, aliases: ['espana'] },
  { id: '144', name: 'Sri Lanka', continent: AS, aliases: ['ceylon'] },
  { id: '729', name: 'Sudan', continent: AF, aliases: [] },
  { id: '740', name: 'Suriname', continent: SA, aliases: [] },
  { id: '752', name: 'Sweden', continent: EU, aliases: ['sverige'] },
  { id: '756', name: 'Switzerland', continent: EU, aliases: ['swiss', 'suisse'] },
  { id: '760', name: 'Syria', continent: AS, aliases: [] },
  { id: '158', name: 'Taiwan', continent: AS, aliases: ['roc', 'formosa', 'republic of china'] },
  { id: '762', name: 'Tajikistan', continent: AS, aliases: [] },
  { id: '834', name: 'Tanzania', continent: AF, aliases: [] },
  { id: '764', name: 'Thailand', continent: AS, aliases: ['siam'] },
  { id: '626', name: 'Timor-Leste', continent: AS, aliases: ['east timor', 'timor leste'] },
  { id: '768', name: 'Togo', continent: AF, aliases: [] },
  { id: '776', name: 'Tonga', continent: OC, aliases: [] },
  { id: '780', name: 'Trinidad and Tobago', continent: NA, aliases: ['trinidad', 'tobago'] },
  { id: '788', name: 'Tunisia', continent: AF, aliases: [] },
  { id: '792', name: 'Turkey', continent: AS, aliases: ['turkiye'] },
  { id: '795', name: 'Turkmenistan', continent: AS, aliases: [] },
  { id: '798', name: 'Tuvalu', continent: OC, aliases: [] },
  { id: '800', name: 'Uganda', continent: AF, aliases: [] },
  { id: '804', name: 'Ukraine', continent: EU, aliases: [] },
  { id: '784', name: 'United Arab Emirates', continent: AS, aliases: ['uae', 'emirates'] },
  { id: '826', name: 'United Kingdom', continent: EU, aliases: ['uk', 'great britain', 'britain', 'england', 'gb'] },
  { id: '840', name: 'United States', continent: NA, aliases: ['usa', 'us', 'america', 'united states of america'] },
  { id: '858', name: 'Uruguay', continent: SA, aliases: [] },
  { id: '860', name: 'Uzbekistan', continent: AS, aliases: [] },
  { id: '548', name: 'Vanuatu', continent: OC, aliases: [] },
  { id: '336', name: 'Vatican City', continent: EU, aliases: ['holy see', 'vatican'] },
  { id: '862', name: 'Venezuela', continent: SA, aliases: [] },
  { id: '704', name: 'Vietnam', continent: AS, aliases: ['viet nam'] },
  { id: '887', name: 'Yemen', continent: AS, aliases: [] },
  { id: '894', name: 'Zambia', continent: AF, aliases: [] },
  { id: '716', name: 'Zimbabwe', continent: AF, aliases: [] },
]

export const TOTAL = ALL_COUNTRIES.length

export const CONTINENT_OF: Record<string, ContinentKey> = Object.fromEntries(
  ALL_COUNTRIES.map((c) => [c.id, c.continent]),
)

export const BY_CONTINENT: Record<ContinentKey, Country[]> = CONTINENTS.reduce(
  (acc, { key }) => {
    acc[key] = ALL_COUNTRIES.filter((c) => c.continent === key).sort((a, b) =>
      a.name.localeCompare(b.name),
    )
    return acc
  },
  {} as Record<ContinentKey, Country[]>,
)
